int echo(char* var);
int exec(char* programs[], char* policy);
int help();
int cd(char* dirname);
int ffork(char** args, int args_size);
int ls();
int mmkdir(char* dirname);
int touch(char* filename);
int print(char* var);
int quit();
int run(char* script);
int set(char* var, char* value);
